### ISSUE TITLE
test_ops.jl-> ERROR: LoadError: UndefVarError: FourthOrderTensor not defined

### ISSUE THREAD

**Issue by OVGULIU** [KristofferC/Tensors.jl#114]
ERROR: LoadError: UndefVarError: FourthOrderTensor not defined

**Comment by fredrikekre** [comment]
?

**Comment by OVGULIU** [comment]
FourthOrderTensor not defined

**Comment by fredrikekre** [comment]
That just repeats the title, please at least show what code you ran.

**Comment by OVGULIU** [comment]
from test_ops.jl

**Comment by fredrikekre** [comment]
Again
>  please at least show what code you ran.

Did you just run the individual test files? They are not standalone and meant to be executed via Pkg.test

**Comment by OVGULIU** [comment]
thank you! now it  is solved!
Kind regards!
