### ISSUE TITLE
Support + and - operators for a Tensor and a literal value

### ISSUE THREAD

**Issue by cfbaptista** [KristofferC/Tensors.jl#117]
I noticed that not all basic binary operators are defined for a Tensor and a literal value. I can do this:

```
using Tensors

T = Tensor{1, 3, Float64}(rand(3))
3-element Tensor{1,3,Float64,3}:
 0.769345151859792  
 0.49053491380559344
 0.5374616581398959

T * 5
3-element Tensor{1,3,Float64,3}:
 3.84672575929896  
 2.452674569027967 
 2.6873082906994794

T / 5
3-element Tensor{1,3,Float64,3}:
 0.1538690303719584 
 0.09810698276111869
 0.10749233162797918
```

But I cannot do this:

```
T + 1
ERROR: MethodError: no method matching +(::Tensor{1,3,Float64,3}, ::Int64)
```

or this:

```
T - 1
ERROR: MethodError: no method matching -(::Tensor{1,3,Float64,3}, ::Int64)
```

**Comment by fredrikekre** [comment]
That is very much intended, note that you can't even do that for regular `Array`s. This package implements tensor operations, and scalar * tensor and tensor / scalar is well defined, but when are you actually using scalar + tensor?

**Comment by cfbaptista** [comment]
Ah okay I see. `Array`s ineed do not support it as well. `StaticArrays` on the other hand do. But I see your point staying true to the perspective of well-defined Tensor operations.

**Comment by fredrikekre** [comment]
> `StaticArrays` on the other hand do.

Yea, I would consider that a bug in StaticArrays, https://github.com/JuliaArrays/StaticArrays.jl/issues/627.
