### ISSUE TITLE
Suggestion: add the other double contraction

### ISSUE THREAD

**Issue by soraros** [KristofferC/Tensors.jl#130]
add support for double contraction defined as
a = B:C = B_ij C_ji

**Comment by fredrikekre** [comment]
I have never seen this product. Isn't this usually written as the double contraction with the transpose? E.g. `a = B : Cᵀ`?

**Comment by soraros** [comment]
Yes, this is just B : C^T. It’s written as B : C^T IF you adopt the convention ijij. My point is if we have this product, we can translate formula with the ijji convention directly.
 [conventions](https://math.stackexchange.com/questions/348739/double-dot-product-vs-double-inner-product)

**Comment by KristofferC** [comment]
Seems a bit like too much overhead to introduce a new operator instead of just writing `A : B'` (which probably is how the operator would be implemented).

**Comment by soraros** [comment]
Ok, fair enough.
