### ISSUE TITLE
`symmetric` breaks automatic differentiation

### ISSUE THREAD

**Issue by KeitaNakamura** [KristofferC/Tensors.jl#40]
```julia
julia> Isym = one(SymmetricTensor{4,3});

julia> gradient(symmetric, rand(Tensor{2,3})) ≈ Isym
false

julia> gradient(symmetric, rand(SymmetricTensor{2,3})) ≈ Isym
true

julia> gradient(x -> (x+x')/2, rand(Tensor{2,3})) ≈ Isym
true

julia> gradient(x -> (x+x')/2, rand(SymmetricTensor{2,3})) ≈ Isym
true
```

This is because `symmetric` changes type of argument from `Tensor` to `SymmetricTensor`, and AD in Tensors doesn't support this change in `_extract_gradient`. I'm not sure that this is really problem in this package. Should I carefully use by myself?

**Comment by KristofferC** [comment]
Unfortunately, I think it is expected that to have the same output type as input type. Perhaps we should type assert that?

**Comment by KeitaNakamura** [comment]
I think it would be nice if we can know our mistakes by type assert. :)

**Comment by KristofferC** [comment]
Maybe you can attempt to fix it?

**Comment by KeitaNakamura** [comment]
Sure. I will try it. BTW, how about following result?

```julia
julia> gradient(x -> 2, rand(Tensor{2,3})) # error

julia> ForwardDiff.gradient(x -> 2, rand(3,3))
3×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0
```

This is also expected?

**Comment by KristofferC** [comment]
No, that's not ideal. In this case (when a Dual number does not get returned) we should just create a tensor of zeros of the correct size.

**Comment by KeitaNakamura** [comment]
Okey. I'm going to fix this as well.
