### ISSUE TITLE
Suggestion: Implement numerical differentiation

### ISSUE THREAD

**Issue by KeitaNakamura** [KristofferC/Tensors.jl#47]
We already have automatic differentiation which is definitely much better than numerical differentiation regarding both of accuracy and speed. Some computations, however, require use of numerical differentiation, for example, numerical computation of consistent (algorithmic) tangent modulus:

* [Numerical computation of algorithmic (consistent) tangent moduli in large-strain computational inelasticity](http://www.sciencedirect.com/science/article/pii/0045782596010195)
* [Introduction to Finite Strain Theory for Continuum Elasto-Plasticity](http://as.wiley.com/WileyCDA/WileyTitle/productCd-1119951852.html), pp. 315.

If you accept to implement numerical differentiation in Tensor.jl, I'm happy to code it.

**Comment by KristofferC** [comment]
There is actually no need for numerical differentiation for consistent tangent computations. Please see page 28 and forward in https://dl.dropboxusercontent.com/u/14340581/kc_on_ad.pdf.

**Comment by KristofferC** [comment]
Also, when doing plasticity you typically don't have a Tensor -> Tensor function. You have a vector of tensors and scalars [sigma, kappa, mu,...]  that maps to a residual (also a vector) and you want to find sigma, kappa so that the residual is zero. You could already use numerical differentiation on this function. since it is just a normal vector -> vector function.

**Comment by KeitaNakamura** [comment]
Cool! I mean we could do this?

```julia
julia> ϵ = one(Tensor{2,3});

julia> σ = return_mapping(ϵ); # I have a return_mapping function including some iterations inside

julia> consistent_tangent = gradient(return_mapping, ϵ); # I can get a consistent tangent modulus?
```

**Comment by KristofferC** [comment]
No, that will not work. In your return mapping you have a function `r(σ, ϵ)` that you solve for `r = 0`. The consistent tangent is then: 

```
drdσ = gradient(σ -> r(σ, ϵ),  σ)
drdϵ = gradient(ϵ -> r(σ, ϵ),  ϵ)
dσdϵ = drdσ \ drdϵ
```

**Comment by KeitaNakamura** [comment]
Could you tell me references about computations of consistent tangent modulus from jacobian if you have?

**Comment by KristofferC** [comment]
Yes, you use the final jacobian together with `drdϵ` (many times `drdϵ` =  the elastic modulus) to compute the consistent tangent. I don't have many references for it, but the mathematics is just implicit differentiation: https://en.wikipedia.org/wiki/Implicit_function#General_formula_for_derivative_of_implicit_function

**Comment by KeitaNakamura** [comment]
Thank you again. I would close this issue.
