### ISSUE TITLE
Pkg.test("Tensors") freezes on Julia 0.5 for Tensors.jl 0.6.x releases

### ISSUE THREAD

**Issue by tkelman** [KristofferC/Tensors.jl#63]
See https://github.com/JuliaCI/pkg.julialang.org/commits/gh-pages/logs/Tensors_0.5.log, it's been timing out on pkgeval since 0.6.0 was tagged so no new logs have been uploaded. What might cause this, considering Travis was apparently passing at the time?

**Comment by KristofferC** [comment]
I think it might be https://github.com/JuliaLang/julia/issues/21081 that is fixed on 0.6.

**Comment by KristofferC** [comment]
Don't think we will investigate this.

**Comment by tkelman** [comment]
Should all the Tensors 0.6.x releases be marked julia-0.6-only or will this just be broken permanently on julia 0.5?

**Comment by fredrikekre** [comment]
IIUC it is not broken; running the tests just takes a very long time for some of the releases on 0.5.
