### ISSUE TITLE
Suggestion: Implement block like array

### ISSUE THREAD

**Issue by KeitaNakamura** [KristofferC/Tensors.jl#65]
I'm writing code about return mapping in my research recently, and I thought it would be useful if we have block like array that can store tensors and scalars. Something like:

```julia
julia> A = one(SymmetricTensor{2,3});

julia> B = @block [A, 10.0]
  1.0
  1.0
  1.0
  0.0
  0.0
  0.0
 10.0

julia> isa(B, AbstractVector)
true

julia> @getblock B[1]
3×3 Tensors.SymmetricTensor{2,3,Float64,6}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

julia> @getblock B[2]
10.0

julia> @setblock B[1] = 2A
  2.0
  2.0
  2.0
  0.0
  0.0
  0.0
 10.0
```

In the implementation, we could use mandel form for symmetric tensors. I'm not sure whether this block array should be in `Tensors.jl` or not, so I would like to ask your opinion.

**Comment by KristofferC** [comment]
You can checkout https://github.com/KristofferC/BlockArrays.jl. The problem however is that mixing scalars and tensors will likely make things slow (type unstable) unless you are very careful.

**Comment by KeitaNakamura** [comment]
> You can checkout https://github.com/KristofferC/BlockArrays.jl.

**Comment by KeitaNakamura** [comment]
In this case, we could know the size of `BlockArray` in compile time, so we may make like `getblock` function without type instability.

**Comment by KristofferC** [comment]
But `getblock` will return a scalar / tensor depending on the **value** of the index? You could perhaps to it by indexing with some value type (like `Val`). I usually use Voigt notation when I have to mix tensors / vectors and scalars because the blockarray is usually used in some linear solver that needs a normal matrix anyway.

**Comment by KeitaNakamura** [comment]
> But getblock will return a scalar / tensor depending on the value of the index? You could perhaps to it by indexing with some value type (like Val).

Yes, I plan to use `Val{i}` where `i` is index of block.

Do you think that this should be implemented not in `Tensors.jl`?

**Comment by KeitaNakamura** [comment]
> I usually use Voigt notation when I have to mix tensors / vectors and scalars because the blockarray is usually used in some linear solver that needs a normal matrix anyway.

BTW, why couldn't we use mandel form in that case?

**Comment by KristofferC** [comment]
Yes that too of course.

**Comment by KristofferC** [comment]
I am not sure it fits in this package. Maybe! :) If you get something working I would be happy to look at the code and see how it is used.
