### ISSUE TITLE
Symmetric 4th order tensor - minor or major symmetry?

### ISSUE THREAD

**Issue by mohamed82008** [KristofferC/Tensors.jl#80]
Hi,

I was going through JuaFEM and my curiosity led me to this package to understand the parameter `M` in `Tensor{order, dim, T, M}`. It seems that the `data` is stored in a Tensor object as a tuple, rather than a static array, to save memory with symmetric tensors I suppose, and `M` is the number of elements in the data tuple.

So for a 4th order symmetric tensor, do you mean minor symmetry or major symmetry? Taking for example the 4th order stiffness tensor which has both minor and major symmetry that is C_{ijkm} = C_{jikm} = C_{ijmk} = C_{kmij}. From the following piece of code starting at line 57 in the file Tensors.jl, it seems that you are using minor symmetry only. Is this intentional or a bug?
```
@pure function n_components(::Type{SymmetricTensor{4, dim}}) where {dim}
    n = n_components(SymmetricTensor{2, dim})
    return n*n
end
```
To use major symmetry as well, it would be something like this:
```
@pure function n_components(::Type{SymmetricTensor{4, dim}}) where {dim}
    n = n_components(SymmetricTensor{2, dim})
    return n_components(SymmetricTensor{2, n})
end
```

**Comment by fredrikekre** [comment]
We define fourth order symmetric tensors (`SymmetricTensor{4}`) to possess 1st and 2nd minor symmetric, that is `C_ijkl == C_jikl` and `C_ijkl == C_ijlk`. You can still create a minor and major symmetric 4th order tensor:
```julia
julia> λ = 0.6; μ = 0.4;

julia> δ(i,j) = i == j ? 1.0 : 0.0;

julia> g(i,j,k,l) = λ*δ(i,j)*δ(k,l) + μ*(δ(i,k)*δ(j,l) + δ(i,l)*δ(j,k));

julia> C = SymmetricTensor{4, 3}(g);

julia> isminorsymmetric(C)
true

julia> ismajorsymmetric(C)
true
```

**Comment by mohamed82008** [comment]
Interesting, so it can detect major symmetry but it still stores each entry twice:
```
julia> length(C.data)
36
```

**Comment by KristofferC** [comment]
> which would be a huge hit

Hm, for a million elements you would waste on the order of megabytes. Compare that to your global stiffness matrix.

Having a major symmetric tensor might be interesting but it is not something that is worked on.

**Comment by mohamed82008** [comment]
Well,  maybe but that's probably an argument for not having symmetric tensors at all cuz not having minor symmetry as well would cost roughly twice as many megabytes for a million elements. And actually if the global matrix is sparse, the memory used by it and that of some element-wise 4th order tensor should be comparable, same big O, so I don't see your point. Of course an element wise stiffness matrix is a nearly crazy idea even for composites, but u know for sake of argument. If u r against the idea then nevermind, I will see when I can implement it and evaluate the savings, then we can re-discuss it.

**Comment by KristofferC** [comment]
It is not only about storage but also about computations. `C_ijkl s_kl` and `s_ij C_ijkl`are both symmetric second order tensors when `C` has minor symmetry and `s` is symmetric. This operations can thus be computed more efficiently than if one disregard symmetry. I don't think you gain anything computation wise by adding major symmetry. Of course, using less memory has the advantage of cache locality so it would be interesting to see some benchmarks.

**Comment by mohamed82008** [comment]
Actually, I think you could save some time when computing `s_ij C_ijkl s_kl` in one loop. If `i != j != k != l`, then it is multiplied by 4, if `i == j && k != l` or `k == l and i != j`, it is multiplied by 2 and if all are equal then it is counted once only.

**Comment by louisponet** [comment]
Sorry to barge in on this. The documentation on `symmetric(a)` where `a` is a 4th rank tensor, this results I believe in a minor symmetric tensor rather than a minor symmetric. From the documentation it seems that it should be a minor symmetric one though?

**Comment by KristofferC** [comment]
I think you have a typo somewhere there? One of those minor should be major?

**Comment by louisponet** [comment]
yes, updated
