### ISSUE TITLE
Check this 

### ISSUE THREAD

**Issue by fredrikekre** [KristofferC/Tensors.jl#95]
https://github.com/KristofferC/ContMechTensors.jl/issues/112

**Comment by fredrikekre** [comment]
Yea I know, but I think we need to update some tests which uses e.g. `vecnorm`.

**Comment by dkarrasch** [comment]
I see. As for `vecnorm` specifically, I couldn't find any occurence in the tests. The tests on `norm(Tensor)` in `test_misc.jl` seem to test against `sqrt(sum(abs2, Array(t)[:]))` explicitly, not against some `Base.norm` or `LinearAlgebra.norm`.

**Comment by fredrikekre** [comment]
Well, at least that can be updated to just `norm` now then :)
